@startmindmap

* noun+s/es
** 1.s \n f,k,p,t,θ
***_ book /bʊk__s__/
***_ bats /bæt__s__/
***_ moths  /mɒθ__s__/
** 2.z \n b,d,g,l,m,n,...
***_ goes/ɡəʊ__z__/
** 3.iz \n b,p,d,r
***_ babies /ˈbeɪ.bi__z__/
***_ puppies /ˈpʌp.i__z__/
** 4.???
***_ knife -> knives
***_ wolf/wʊlf/ -> wolves

* v+s/es
* v+ed

@endmindmap