@startuml

binary "CDR" as CDR
binary "CDR6" as CDR6
concise "Case 1 Refunded on same day" as C1
concise "Case 2 Refunded on next day" as C2
'clock "Refund Job" as BS with period 300 pulse 5 offset 50
'clock   "Time" as T1 with period 10 pulse 1 offset 0
'concise "Time" as T
concise "Report Date" as R

@00:00:00
note top of CDR6
<b><color:red>CDRJob@Bean cron: 0 10 __07/13/15/19__ * * ?
'(4)07:10 AM, 01:10 PM, 03:10 PM, 07:10 PM
cbrp_vsalesjournal_domestic_{__DDMMYYYY__}_{__HHMM__}.0001.txt
'impTime:Task2(0600)|Task3(1200)|Task1(0000)|Task4(1800)
end note
note top of CDR
<b><color:red>cron: 0 10 __07/13/15/19__ * * ? || (2)04:00 AM and 6:15 AM
cbrp_vsalesjournal_domestic_{DDMMYYYY}.0001.txt
end note


@CDR6
7:10:00 is high
note top of CDR6: <color:red>JobTask2(0600)
7:20:00 is low
13:10:00 is high
note top of CDR6: <color:red>JobTask3(1200)
13:20:00 is low
15:10:00 is high
note top of CDR6: <color:red>JobTask1(0000)
15:20:00 is low
19:00:00 is high
note top of CDR6: <color:red>JobTask4(1800)
19:20:00 is low

@CDR
4:00:00 is high
note top of CDR: \nasa
4:10:00 is low
6:15:00 is high
6:25:00 is low


'R is "Report T"
'note top of C1
'Status: TRANSACTION_COMPLETED
'HubStatus: COMPLETED
'end note

'@24:00:00
'highlight 500 to 1000 #Gold;line:DimGrey : Report T + 1

@enduml