@startmindmap
* Vocabulary
**:--Adj--
<b><color:red>discrete /dɪˈskriːt/</b>(adj): rời rạc
<b><color:red>__concrete__</b> information: thông tin __cụ thể__
;
**:--Adv--

;
**:--Other--
somewhat
;
left side
**:--Verb--
<b><color:red>infer/ɪnˈfɜːr/</b>: suy luận
' to guess that something is true because of the information that you have
<b><color:red>pick out</b>: chọn ra
synthesize/ˈsɪnθəsaɪz/: tổng hợp
;
**:--Noun--
stretches /stretʃ/ (v,n)
<b><color:red>__straightforward__</b> factual: thực tế __đơn giản__
;
** family words:
*** infer(v[t])
**** inferences(noun[c])
*** synthesize(v[t])\n/ˈsɪnθəsaɪz/
**** synthesis(noun[c,u])\n/ˈsɪnθəsɪs/
@endmindmap