@startuml
title CHECK remit support NETSCLICK

concise "Payment Status" as PS
concise "User Request" as UR
concise "RemittanceStatus-HappyCase" as HC
concise "UnhappyCases" as UC

@0
note top of UR
<color:green>POST /api/v2/remittance
Headers:
- <color:red>partner-id,correlation-id,x-api-key,cipher-text
timestamp,nonce,accept-language
'--check-correlation-id--
- <color:blue>__(*)device-id__
Body:
- <color:red>beneMsisdn,amount,currencyFlag(0|1),serviceId,
<color:red>remitFlag=__CHECK__(SUBMIT)
'--mobileDeviceId--
'- <color:blue>__(*)deviceInfo__</color>:For Forter integration
- <color:blue>__(*)cardId__</color>:ML unique UUID
- <color:blue>__paymentMode__</color>(dashwallet|netsclick)
end note
UR is "CHECK"

@50
UR is "GetRequiredInformation"
note bottom of UR
- Bene Information(Customer Service)
- CustomerExtensionData(Utility Service)
- Service Detail(Product Service)
end note

@400
UR is "Create Transaction:Check Grey"

UC is "Don't impact to customer balance"

note top of UR
<color:green>SUCCESSFUL CASE
Headers:
- <color:green>check-correlation-id
Body:
- <color:red>msisdn,beneMsisdn,localCurr,
<color:red>localAmount,beneCurr,beneAmount,
<color:red>localNetAmount,fxRate
,beneAmountWithTax,localcomm,localTax
- <color:green>__paymentMethod__,__cardId__</color>(netsclick|wallet|paynow)
end note

note bottom of UC
PAYMENT_VALIDATED_FAILED ???
end note

@600
HC is "Don't impact to customer balance"

note bottom of HC
PAYMENT_VALIDATED
- check-correlation-id
- paymentMethod
- cardId
- msisdn,beneMsisdn, ...
end note

@800
UR is "Pre Validate:Forter & AML" #LightCyan;line:Aqua

note bottom of HC
PAYMENT_ACCEPTED
* prevent double SUBMIT
end note

@1000
UR is "Payment"  #red;line:Aqua
note bottom of HC
PAYMENT_RESERVED
end note

note top of UC
PAYMENT_TIMEOUT
end note

note bottom of UC
PAYMENT_RESERVED_FAILED
end note

UC is "Impact to customer balance"

@1150


@1200
UR is "Confirm Transaction"
HC is "Impact to customer balance"

@1250
note bottom of HC
TRANSACTION_SUBMITTED
end note
note top of UC
TRANSACTION_TIMEOUT
end note

note bottom of UC
TRANSACTION_FAILED
end note

@1450
UR is "Batch Job" #yellow;line:Aqua
note bottom of UC
PAYMENT_REFUND_REQUIRED
end note

@1600
UR is "Approve with soft" #LightCyan;line:Aqua




@1800
UR is "Callback"
note bottom of HC
TRANSACTION_COMPLETED
end note
note top of UC
TRANSACTION_REVERSED
end note

note bottom of UC
TRANSACTION_DECLINED
TRANSACTION_REJECTED
<color:red>TRANSACTION_CANCELLED
<color:red>auto or manually
end note


@2050
UR is "Batch Job" #yellow;line:Aqua
HC is {hidden}

note bottom of UC
REFUNDED
REFUND_FAILED
end note


@2200
'T1 is {-}
@enduml