@startmindmap
caption Labels & Codes
title Dictionary

*[#Orange] <&flag>Cambridge
**[#lightgreen] Verbs
*** <color:red>[T]
****_ <color:red>Transitive verb: a verb that has an object.
*** <color:red>[I]
****_ <color:red>Intransitive verb: a verb that has no object.
*** auxiliary verb
****_ The verbs be, have and do, which combine with other verbs to make different forms like passives, questions and the continuous.
*** modal verb
****_ Verbs, such as must and can, that add meaning such as certainty and obligation.
*** past simple
****_ The past simple form of the verb (eat ate eaten).
*** past participle
****_ The past participle of the verb (eat ate eaten).
*** present participle
****_ The present participle of the verb (tying tied).
*** phrasal verb
****_ A verb followed by an adverb or a preposition.

left side
**[#lightgreen] Nouns
*** <color:red>[C]
****_ Countable noun: a noun that has a plural.
*** <color:red>[U]
****_ Uncountable or singular noun: a noun that has no plural.
*** <color:red>[S]
****_ A singular noun.
*** plural
****_ The plural form of a noun.
*** ...

**[#lightgreen] Adjectives
*** ...
*** comparative
****:The form of an adjective or adverb that expresses
a difference in amount, number, degree, or quality.;
*** superlative
****:The form of an adjective or adverb that expresses that
the thing or person being described has more of the particular
quality than anything or anyone else of the same type.;
**[#lightgreen] Others


@endmindmap