@startmindmap
'https://plantuml.com/mindmap-diagram

caption English Vocabulary
title Phraser Verb

*[#Orange] <&flag>Phraser Verb

left side
'There are two types of phrasal verbs.
'**[#lightgreen] Inseparable and Separable
**: <b>Inseparable and Separable
'-- Inseparable --
1.Inseparable phrasal verbs <color:red><b>cannot be separated</color> by other words.
'-- Separable --
2.Separable phrasal verbs <color:red><b>can be broken up</color> by other words
'+) A + Object + B
'+) A + B + Object
Note: If the object is a pronoun, it <color:red><b>must always</color> be placed in the middle of a separable phrasal verb.
Example: Pick it up and carry it to the kitchen
;

right side

'Transitive phrasal verbs use a direct object
**[#lightgreen] 1.Transitive + sth
***_ <color:red><b>Put Up With</color>: Chịu đựng
***_ <color:blue><b>get over [x]</color>: to recover from or overcome something (Vượt qua)
***_ <color:blue><b>get through [x]</color>: to complete or endure an unpleasant experience


'***_ <color:blue>back [x] up</color>: to support or defend someone
'****_ When the class was making fun of me, only the teacher backed me up.
***_ <color:blue>check [x] out</color>: to examine a person or thing;
'when used in reference to a person, can connote looking at them with romantic or sexual interest
'****_ I’ll check the contract out. / I’ll check out the contract.
***_ <color:blue>cheer [x] up</color>: to make someone happy, especially if they were previously sad
'***_ <color:blue>clean [x] up</color>: to tidy an area
'***_ <color:blue>come between [x]</color>: to interfere with a relationship between two people
'***_ <color:blue>come down with [x]</color>: to catch an illness (sự ốm yếu)
'***_ <color:blue>come out of [x]</color>: to happen as a consequence of another event
***_ <color:blue><b>come up with [x]</color>: to think of an idea, especially as the first person to do so, or to produce a solution
'count on [x]
'crack down on [x]
'dive into [x]
***_ <color:blue>get [x] across</color>: to successfully communicate or explain something
***_ <color:blue>get along with [x]</color>: to be on harmonious terms with someone
***_ <color:red><b>let [x] down</color>: to disappoint someone
***_ <color:blue>get along with [x]</color>: to be on harmonious terms with someone
***_ <color:blue>put [x] on</color>: to dress oneself in
***_ <color:blue>get along with [x]</color>: to be on harmonious terms with someone
***_ <color:blue>get along with [x]</color>: to be on harmonious terms with someone


'***_ come out of [x] to happen as a consequence of another event


**[#lightgreen] 2. Intransitive
'Intransitive phrasal verbs (Nội động từ) do not use an object
'Inseparable phrasal verbs cannot be split up; the verb and the particle must staytogether.
'All intransitive phrasal verbs are inseparable.
'Some transitive phrasal verbs are also inseparable
***_ <color:blue><b>carry on</color>: Tiếp tục ~ continue
***_ <color:blue><b>go on</color>: to continue
***_ <color:blue><b>go over</color>: to review or look at something
***_ <color:blue>call around</color>: to contact multiple people
'****_ Roy called around to find a nearby mechanic.

***_ <color:blue><b>come around</color>: to change one’s opinion or see a new point of view
***_ <color:blue><b>come up</color>: \n-to arise as a topic of discussion or receive attention\n-to approach \n-to present itself or occur, as of an event or situation
***_ <color:blue><b>TMP</color>: TMP




left side
**[#lightblue] Learned
'***_ <color:blue><b>go over</color>: đi qua
***_ <color:blue><b>break down</color>: to stop working, especially in reference to machines
'****_ The ice cream machine at McDonald’s often breaks down.
***_ <color:blue><b>calm down</color>: to relax after an energetic or irritated state
'****_ I need a few minutes to calm down after that match.
***_ <color:red><b>give up</color>: to accept defeat, quit, or surrender
***_ <color:blue><b>give [x] up</color>: to stop consuming or doing something, often a habit
***_ <color:blue><b>go ahead</color>: to proceed or move forward
***_ <color:blue><b>let [x] know</color>: to tell someone something
***_ <color:blue><b>look after [x]</color>: to take care of someone or something
***_ <color:blue><b>run out of [x]</color>: to use all of or drain the supply of something
***_ <color:blue><b>shut [x] off</color>: to turn off, especially a machine
***_ <color:blue><b>take [x] out</color>: to move something outside
***_ <color:blue><b>think [x] over</color>: to consider something
***_ <color:blue><b>throw [x] away</color>: to dispose of something
***_ <color:blue><b>turn [x] down</color>: to reject or say no to someone

**[#lightblue] Learned2
***_ <color:blue><b>listen to</color>
***_ <color:red><b>wait for</color>
***_ <color:blue><b>ask for</color>
***_ <color:blue><b>pay for</color>
***_ <color:red><b>belong to</color>
***_ <color:red><b>thinking about to</color>
***_ <color:blue><b>thank someone for</color>
***_ <color:blue><b>apologies for</color> xin lỗi vì

* get
** <b><color:red>up
*** at 6:30 o'clock
** <b><color:red>on</b> ~ to have a good relationship:
*** with my sister
** <color:red><b>over
*** a cold

* turn
-- up
-- down
*** ... the --stero-- stereo = made it not so loud
*** <b><color:red>... the invitation</b> = refused it
right side
** on
** of

* go
** <color:blue>on ~ continue
** <color:red><b>off

* put
** put sth on

* come
** on
*** we're late

* take
** off
*** at 12:30 = leaves the ground
*** <b><color:red>her shoes</b> = remove them from her feet

* do
** <b><color:red>up
*** her coat (cô ấy đã sửa lại chiếc áo khoác của mình)
*** her flat (cô ấy đã dọn dẹp căn hộ của mình)

* look
left side
** for
***_ a key
** after
***_ a children
***_ /ˈpeɪ.ʃənt/ a patient
right side
** at
***_ a book
** forward to
***_ a party
***_ my birthday


'header
'My super header
'endheader

'center footer My super footer

'legend right
'  Short
'  legend
'endlegend
@endmindmap
