@startmindmap
caption English Vocabulary
title Clothing

*[#Orange] <&flag>man
left side
**[#lightgreen] Clothing
***_ <color:red><b>sweater</color>: áo len
***_ <color:red>shirt</color>: áo sơ mi
***_ <color:red>T-shirt</color>: Áo thun (áo cộc tay)
***_ <color:red><b>cap</color>: mũ lưỡi trai hat vs hat(mũ)
***_ <color:red>suit</color>: bộ đồ com lê
***_ <color:red>shorts</color>: quần short
***_ <color:red>pullover</color>: áo hở cổ
***_ <color:red>jacket</color>: áo khoác
***_ <color:red>trousers</color>: quần dài
***_ <color:red>jeans</color>: Quần jean
***_ <color:red><b>pants</color>: quần dài

right side
**[#lightgreen] Body Part
***_ <color:red><b>wrist</color>: cổ tay
'***_ <color:red>Abdomen</color>: bụng ~ stomach
'***_ <color:red>abs</color>: cơ bụng
***_ <color:red><b>ankle</color>: mắt cá
'***_ <color:red>armpit</color>: nách
***_ <color:red><b>beard</color>: râu
***_ <color:red>cheek</color>: má
***_ <color:red>chest</color>: ngực
***_ <color:red>chin</color>: cái cằm
***_ <color:red><b>elbow</color>: khuỷu tay
***_ <color:red>eyebrow</color>: lông mày
***_ <color:red>pupil</color>: con ngươi(học sinh) nội tạng
'***_ <color:red>fist</color>: nắm tay
***_ <color:red><b>forehead</color>: trán
'***_ <color:red>goatee</color>: râu dê
'***_ <color:red>hamstrings</color>: gân kheo
***_ <color:red><b>heel</color>: gót chân
***_ <color:red>hip</color>: hông
'***_ <color:red><b>jaw</color>: hàm
***_ <color:red><b>knee</color>: đầu gối
***_ <color:red><b>nostril</color>: lỗ mũi
***_ <color:red><b>palm</color>: lòng bàn tay
'***_ <color:red><b>pinky</color>: ngón út
'***_ <color:red><b>waist</color>: thắt lưng
***_ <color:red><b>toes</color>: ngón chân
***_ <color:red><b>tongue</color>: lưỡi
'***_ <color:red><b>Uvula</color>: lưỡi gà
***_ <color:red><b>vocal cords</color>: dây thanh
***_ <color:red><b>wisdom tooth</color>: răng khôn
'arm, back, ear, eye, face, fingers, foot, hair, hand, head, leg, lip,
'mouth, muscles, nails, neck, nose, shoulder, skin, throat, tooth, neck

left side
**[#lightgreen] Organ vs Viscera
***_ <color:red><b>Kidney</color>: Quả thận
***_ <color:red><b>intestine</color>: ruột
***_ <color:red>Pancreas</color>: Tuyến tụy
***_ <color:red>thyroid</color>: tuyến giáp
***_ <color:red>nerves</color>: dây thần kinh
'lungs, lives, stomach, heart, brain, ribs

**[#lightgreen] Action Verbs
***_ <color:red><b>crawl</color>: bò

@endmindmap