@startmindmap
caption English Vocabulary
title Human

*[#Orange] <&flag>Daily Activities
left side
**[#lightblue] have/had/had
---_ have ...
----_ lunch | dinner | breakfast | a meal | sth to eat
----_ a party | a meeting | a <color:red><b>competition</color> | a game
----_ a lesson | an a <color:red><b>exam</color>(vs example)
----_ a cup of coffee/tea | drink | a <color:red><b>sandwich</color>
----_ a shower | a bath | a swim | a sauna
***_ Expression
----_ <color:red>have a look = look at it
----_ have a go = ride it
----_ have a moment= have some time
***_ <color:red><b>have to
***_ <color:red><b>have got(speaking/informal)</color>>= have (writing/formal)

**[#lightblue] go/went/gone
***_ <color:red><b>Here -go-> there </color>
***_ on <b>foot</b> or in some kind of (--transpot--) <color:red><b>transport
****_ to emphasize on foot we use <color:red><b>walking
***_ go + <b>preposition
****_ go in/out/into/up/down/back/<color:red><b>away
***_ go + <b>V-ing
****_ going shopping| going sightseeing| going fishing| go swimming| go dancing|
***_ be going to (future plan)

**[#lightblue] do/did/done
***_ do as <color:red><b>auxiliary</color>
****_ do you like | yes, I do
***_ do as general verb
****_ what do you do to relax VS what are you doing?
***_ do + task
****_ homework|the washing|your best

**[#lightblue] make/made/made
***_ make ...
****_ <color:red><b>coffee|dinner|
***_ make a ...
****_ <color:red><b>photocopy|film|video|noise|
***_ it make me (feel-optional) ...
****_ <color:red><b>tired|angry|sad

right side
**[#lightblue] come/came/come
***_ <color:red><b>Here <-come- there </color>
***_ + preposition
****_ in/out/out of/back/home/here/from/<b>along(=come with us)
****_ <color:red><b>around/across/up ???
****_ come and see me = visit me


**[#lightblue] take/took/taken
***_ <color:red><b>Here -take-> there </color>
***_ with time: it + take + person + time
****_ It <b>take</b> me <b>more than 1 hour</b> to go to my office.
***_ take with --cource-- course
****_ are you <b>taking</b> an english <b>course</b>? Yes
***_ take with bus, car, ...etc
****_ I take the bus to go to work.
***_ take something with you
****_ Take an --unbrelar-- umbrella/some water/

**[#lightblue] bring/brought/brought
***_ <color:red><b>Here -go/take-> there </color>
***_ <color:red><b>Here <-come/bring- there </color>
***_ bring sb something
***_ bring something back

**[#lightblue] get/got/got
***_ <color:red><b>get with adj</color>: for change
****_ light -> <color:red><b>getting dark</color> -> dark
****_ ill -> <color:red><b>getting better</color> -> well
***_ get with noun
***_ <color:red><b>get to</color>(arrived at / reach a place)
***_ other phrasal
****_ <color:red><b>get married/get back/get up/get home/get there

* second
right side
**[#lightblue] Phrasal Verbs
***_ put on, turn down
**[#lightblue] Things
***_ watch TV, wash clothes
**[#lightblue] Talking
***_ say, tell
**[#lightblue] Moving
***_ walk, carry




@endmindmap