@startmindmap
caption English Vocabulary
'title Human

*[#Orange] <&flag>Conjunction
left side
**[#lightblue] <b>connect <color:red>two part of sentence
***_ and: tells you more
***_ but: makes a contrast
***_ because: answers question why?
***_ so: tells you the result
***_ when: answers the question when
***_ before, after: answers the question what happened first
***_ although, though: tells you something --surpricing-- surprising
***_ if: makes a condition

right side
**[#lightblue] Words and Phrases
***_ only: says something is not very big or not very much
***_ even: says something is surprising or unusual.
***_ like: makes a comparison.
***_ than: used after a comparative adjective or adverb
***_ also, too, as well: says something is extra


**[#lightblue] Social Issues
***_ Crime
***_ The Media
***_ Everyday problem
***_ Global problem





@endmindmap