@startmindmap
caption English Vocabulary
title Human

*[#Orange] <&flag>Human
left side
**[#lightblue] Life circle \nBirth, Marriage, Death
***[#lightgreen] Birth
****: Diana <b>had</b> a baby yesterday
It <b>was born</b> at 1AM yesterday
His <b>birthday</b> is October 22th;

***[#pink] Marriage /ˈmær.ɪdʒ/ Hôn nhân
****: Single -> Married
-> widowed /ˈwɪd.əʊd/ góa bụa
-> separated/divorced
- wending: bride + groom
- honeymoon/ got married/ were married;

***[#gray] Death
****: Then Bill <b>become ill</b>
He --deied-- <b>died</b> last year
He <b>died</b> because of a heart attack
Bill is <b>dead</b>
- the <b>funeral</b>(tang lễ);

**[#lightblue] family
***_ grandfather, father, mother, uncle, aunt, cousin, sister, brother ...
***_ <b><color:red>niece /niːs/</b> cháu gái
***_ <b><color:red>nephew /ˈnef.juː/</b> cháu trai

'brother, sister, kids, daughter, son,
**[#lightblue] part of body
***_ ...
***_ <b>waist, hips,
**[#lightblue] clothes
**[#lightblue] describing
***_ height
****_ tall
****_ <b><color:red>medium/ˈmiː.di.əm/</b> height
****_ short
***_ weight
****_ slim(adj,v) mảnh khảnh, thin(adj,v) gầy
****_ fat, overweight
***_ face and head
****_ dark skin, dark hair, <b><color:red>brown</b> (màu nâu) eye
****_ <b><color:red>blonde/blɒnd/ vàng</b> hair, fair skin, long|short hair
****_ a <b><color:red>beard/bɪəd/ râu| moustache /məˈstɑːʃ/ ria
***_ Age
****_ old, young, older, younger, elder, middle-age<b>d
***_ looks
****_ positive: pretty, beautiful, handsome,
****_ negative: ugly/ˈʌɡ.li/ xấu xí
****_ ordinary looking

right side
**[#lightblue] health and illness
***_ very well, fine, feel ill, doctor, sick, <b><color:red>vomit/ˈvɒm.ɪt/(v,n)</b> nôn mửa
***_ an aspirin, a headache, toothache, a cold
***_ hay-fever(n) sốt mùa hè, <b><color:red>sneeze/sniːz/(v)</b> hắt hơi, \n<b><color:red>asthma/ˈæs.mə/(n) bệnh hen suyễn
***_ <b><color:red>mosquito/məˈskiː.təʊ/ \n <b><color:red>malaria/məˈleə.ri.ə/ \n <b><color:red>cholera/ˈkɒl.ər.ə/(n)bệnh tả
***_ a heart attack, <b><color:red>cancer/ˈkæn.sər/</b>(n)bệnh ung thư
***_ diet, --execite-- exercise/ˈek.sə.saɪz/, stress, relax

**[#lightblue] feeling
***_ like,love,hate
****_ prefer ... to ...
***_ happy,sad,tired
' bless you:  ban phước cho bạn

**[#lightblue] describing

**[#lightblue] Countries, languages and people
***_ Continents  /ˈkɒn.tɪ.nənt/

**[#lightblue] Leisure
***_ Holidays
***_ Shops and shopping
***_ Sports
***_ Cinema
***_ Leisure at home:


**[#lightblue] Social Issues
***_ Crime
***_ The Media
***_ Everyday problem
***_ Global problem





@endmindmap