@startmindmap
caption English Vocabulary
title Human

*[#Orange] <&flag>Human
left side
**[#lightblue] -> Birth -> marriage -> death ->
**[#lightblue] family
***_ grandfather, father, mother, uncle,
'brother, sister, kids, daughter, son,
**[#lightblue] part of body
**[#lightblue] clothes
**[#lightblue] describing
**[#lightblue] health and illness
**[#lightblue] feeling
**[#lightblue] describing

right side
**[#lightblue] Leisure
***_ Holidays
***_ Shops and shopping
***_ Sports
***_ Cinema
***_ Leisure at home:


**[#lightblue] Social Issues
***_ Crime
***_ The Media
***_ Everyday problem
***_ Global problem





@endmindmap