@startmindmap
caption English Vocabulary
'title Human

*[#Orange] <&flag>Unknown

**_ in + month/season <b><color:red>--on-- month
**_ I hope Xuan <b><color:red>--will--</b> passes the driving test.

'**[#lightblue] Leisure





@endmindmap