@startmindmap
caption English Vocabulary
'title Human

*[#Orange] <&flag>Irregular Verb\n infinitive -> past simple -> past participle

**[#lightblue] single form
***_ <b><color:red>cost, let, cut, put, hurt, shut

**[#lightblue] two form
***_ <b><color:red>run ran run
***_ <b><color:red>come came come
***_ <b><color:red>become became become
***_ <b><color:red>make made made

**[#lightblue] three forms
***_ <b><color:blue>be was/were been
***_ <b><color:red>fly flew flown
***_ <b><color:red>steal stole stolen
***_ <b><color:red>rise rose risen
***_ <b><color:red>choose chose chosen
***_ <b><color:red>fall fell fallen
***_ <b><color:red>...


@endmindmap