@startmindmap
caption English Vocabulary
'title Human

*[#Orange] <&flag>adverb
left side
**_ always
***_ come to work by bus and MRT
***_ have the meeting at 10:30 o'clock
***_ check the bill on every order
**_ usually
***_ try to write down any information
'but I can't keep it on a good structure
**_ often
***_ swim, run, cycling to improve my health
***_ spend time to read the cartoon to relax
**_ sometime<b><color:red>s</b>
***_ go outside for a meal
right side
**_ now and then
**_ occasionally
***_ hangout with my friend at the weekend
***_ play game with my wife
**_ not often
***_ take an umbrella except heavy raining.
***_ od
**_ hardly ever
***_ win for a game because I play for fun
'however I want to change the ideal, I will play to win
**_ rarely
***_ smoke, I only smoke when I drink a lot and want to get strong feeling
**_ never


*[#Orange] <&flag>Manner = how we do something

--_ fast vs slow
--_ right vs wrong
--_ loud vs quiet
**_ well vs badly
**_ a friendly/unfriendly way.
**_ polite/impolite

*[#Orange] <&flag>Adj
left side
**[#lightgreen] things
***_ good -> better -> best
***_ nice(+) lovely(++) wonderful(+++) --excilent-- <b><color:red>excellent  /ˈek.səl.ənt/
***_ Excellent! Great! Wonderful! Lovely! Perfect!
***_ <b><color:red>bad -> worse -> the worst <b><color:red>(-)
***_ awful <b><color:red>(- -)
***_ terrible <b><color:red>(- - -)
***_ horrible <b><color:red>(- - - -)
**[#lightgreen] people
***_ nice -> wonderful <b><color:blue>(+)
***_ kind <b><color:blue>(+)
***_ lovely, easy-going, happy, intelligent <b><color:blue>(+)
***_ horrible <b><color:red>(-)
***_ difficult, stupid, selfish <b><color:red>(-)
right side
**[#lightgreen] kids
***_ <b><color:blue>(+)</b> good, well-behaved
***_ <b><color:red>(-) naughty /ˈnɔː.ti/
**[#lightgreen] preposition
***_ to: adj + to + Noun
***_ of: adf + of + Noun

*[#Orange] <&flag>Verb/Adj + preposition
left side
**[#lightblue] positive
***_ good at
****_ tennis
****_ playing piano
***_ interested in
***_ proud of
***_ (accustomed /əˈkʌs.təmd/ to) quen với, đã từng: <b><color:blue>used to
***_ làm quen với: <b><color:blue>get used to
'(accustomed /əˈkʌs.təmd/ to sth new)
****_ I'm used to getting up early to study

right side
**[#red] negative
***_ <b><color:red>bad at
***_ <b><color:red>afraid of /əˈfreɪd/</b> --affraid--




*[#Orange] <&flag>Words
**[#lightgreen] uncountable
***_ traffic, sugar, --lguage-- <b><color:red>luggage /ˈlʌɡ.ɪdʒ/
***_ news, information, advice, furniture, weather, air, hard work, travel,
left side
**[#lightgreen] countable
***_ apples, shoes, plates
***_ I drink coffee <b><color:red>vs</b> I drink a cup of coffe.

*[#Orange] <&flag>Words
**[#lightgreen] prefix-
***_ was but not now: <b><color:blue>ex(+noun)
***_ 50% of sth: <b><color:blue>half(+noun or adj)
****_ half-price, half-hour
***_ not: <b><color:red>in,im(+adj)
****_ impossible, informal
***_ before: <b><color:blue>pre
***_ again: <b><color:blue>re(+verb)
***_ not: <b><color:blue>un(+adj or noun)
right side
**[#lightgreen] -suffix
***_ <b><color:blue>(noun+)er or</b>
****_ person
*****_ worker, instructor
****_ machine, thing
*****_ cooker, word processor
***_ <b><color:blue>(adj+)ful</b>: full of
****_ useful, beautiful
***_ <b><color:blue>(adj+)less</b>: without
****_ useless, endless
***_ <b><color:red>(noun+)ology</b>: subject of study
****_ sociology, psychology
***_ <b><color:red>(noun,singular+)ics</b>: subject of study
****_ economics, politics

***_ <b><color:red>(Adj+)ly</b>: Adv
****_ sadly, happily
***_ <b><color:red>(Adj+)ness</b>: abstract Noun
****_ happiness, sadness
***_ <b><color:red>(Noun+)y</b>: Adj
****_ sandy, sunny



@endmindmap