@startmindmap
caption English Vocabulary
'title Human
skinparam {
    wrapWidth 300
}

*[#Orange] <&flag>Confuse word

**[#lightblue] Similar Sound
***_ <b><color:red>quite/quiet \n /kwaɪt/ /ˈkwaɪ.ət/
***_ <b><color:red>lose/loose \n  /luːz/  /luːs/
***_ fell/felt
****_ fall/<b><color:red>fell</b>/fallen: ngã, rơi
****_ <b><color:red>feel</b>/felt/felt: cảm thấy
***_ cooker/cook
****_ <b><color:red>cooker</b>: the thing you cook on
****_ <b><color:red>cook</b>: the person who cooks
***_ here(adv)/hɪər/ <b><color:red>heard /hɪər/

left side
**[#lightblue] Similar Mean
***_ lend/borrow
****_ <b><color:red>lend(cho mượn)
****_ <b><color:red>borrow(mượn)
***_ check/control
****_ <b><color:red>check(kiểm tra)
****_ <b><color:red>control(điều khiển)

***_ <b><color:red>do/make
***_ <b><color:red>take/bring \n HTT / TTH
***_ <b><color:red>say/tell
***_ <b><color:red>speak/talk
***_ <b><color:red>rob/steal \n cướp / ăn cắp
***_ <b><color:red>identify vs __distinguish__ /dɪˈstɪŋ.ɡwɪʃ/
***_ <b><color:red>__affect vs effect__
****_ to affect mean to __influence__
****_ to effect mean to __make sth happen__ / to __bring about__
***_ <b><color:red>increase(v,n) vs increment(n)\n <b><color:red>/ˈɪnkriːs/      /ˈɪnkrəmənt/
****_ increase[C,U] a rise in the number, size, or amount of __something__
****_ increment[C] one of a series of increases (một trong một loạt sự gia tăng)

**[#lightblue] Mixed up
*** time
****_ 12PM->5,6PM<b><color:red> Afternoon
****_ 5,6PM->9,10PM<b><color:red> __Evening__
****_ after 9,10PM<b><color:red> Night
*** <b><color:red>hope
****_ <b><color:red>waiting for
****_ <b><color:red>expect

right side
**[#lightblue] quite similar
***_ <b><color:red>coat/coast \n áo choàng /bờ biển
***_ <b><color:red>boots/boost \n bốt / (v,n) tăng
***_ <b><color:red>cancer / cancel \n/ˈkæn.sər/ /ˈkæn.səl/
***_ <b><color:red>bread / beard \n /bred/ bánh mỳ vs /bɪəd/ râu
***_ <b><color:red> pollution / population \n sự ô nhiễm / dân số
***_ <b><color:red>dive(d) / divide \n /daɪv/ /dɪˈvaɪd/
***_ finance financial / final
***_ <b><color:red>cross(verb) / across (adv,preposition) \n  /krɒs/ đi qua / /əˈkrɒs/ ngang qua, ben kia
***_ <b><color:red>scratch / learn from scratch: học lại từ đầu

left side
**[#lightblue] Grammar
***_ <b><color:red> Why are you crying? __vs__ Why do you cry?
***_ <b><color:red> I used to do __vs__ I am used to doing

**[#lightblue] Family Word
***_ <b><color:red> intent(noun) vs intend(verb)
***_ <b><color:red>courage/ˈkʌrɪdʒ/(n) vs encourage/ɪnˈkʌrɪdʒ/(v)
***_ <b><color:red>accommodate/əˈkɒmədeɪt/(v...) vs accommodation/əˌkɒməˈdeɪʃən/(n)chỗ ở
@endmindmap