@startmindmap

*[#Orange] <&flag>Topics

**_ <b><color:red>1.Subject-Verb Agreement
**_ <b><color:red>2.Preposition Use
**_ <b><color:red>3.Complex grammatical structures
**_ <b><color:red>4.Ways to shorten English sentences
**_ <b><color:red>5.Ways to link 2 sentences

@endmindmap