@startmindmap
caption English Vocabulary
'title Human
<style>
element {
  MaximumWidth 300
}
</style>

*[#Orange] <&flag>Academic \n Vocabulary

**[#lightgreen] Noun
*** Referring to <b><color:red>ideas
****_:<b><color:red>subject</b>: thing which is being discussed, considered or studied
<b><color:red>theme</b>: __main subject__ of a talk, book
<b><color:red>essay topics</b>: used to refer to what one is __studying__ or writing about
<b><color:red>issue</b>: subject/problem which people are thinking/talking about
<b><color:red>theory</b>: <b>statement</b> of the rules on which a subject of study is based on, more generally, an opinion or explanation
model
<b><color:red>__Nature__</b>: main characteristic of sth
principle;
*** connected with <b><color:red>ideas
****_ aspect
****_ feature
****_ scope
****_ <b><color:red>pattern
****_ number
' the study revealed a pattern of results which could be interpreted in either in two ways.
' nghiên cứu đã tiết lộ một dạng kết quả có thể được diễn giải theo hai cách

*** ways of thinking
****_:significance, identification,
<b><color:red>assessment:</b> judgement of the amount, value, quality or importance of ...
<b><color:red>Case <color:blue>+ on</b> arguments, facts and reasons in support of or against sth
<b>Approach</b> way of considering sth
<b><color:red>Perspective</b> different particular or individual ways of considering something.
<b><color:red>awareness(n) /əˈweə.nəs/ <color:blue>+ of</b> having special interest in or experience of sth
<b><color:red>View <color:blue>+ on</b>: research is often also used with the preposition on
methodology: a system of way of studying something;

*** other
****_:reluctant(adj)  /rɪˈlʌk.tənt/ do dự
evolution(n) sự tiến hóa
inaugural(adj) khai mạc
incompetent(adj) /ɪnˈkɒm.pɪ.tənt/ bất tài, không có quyền lực
assignment
' verbs for structuring academic assignment: Động từ cấu trúc bài tập học thuật
;


left side
**[#lightgreen] Verb
*** Structuring academic assignment
****_ <b><color:blue> investigate, consider, analyse, support, affect, include, develop
****_ <b><color:blue>discuss/dɪˈskʌs/, illustrate /ˈɪl.ə.streɪt/
****_ which are part of/included in :<b><color:red>involve
****_ organise and do :<b><color:red>__conduct__
****_ draw sth in order to explain sth :<b><color:red>Illustrate
****_ accepting sth to be true :<b><color:red>Assuming
****_ discover by calculating :<b><color:red>find
****_ <b>judge/dʒʌdʒ/</b> the number or amount of sth and adding,multiplying, subtracting, dividing nubers  :<b><color:red>calculate
****_ show, make clear :<b><color:red>/ˈdem.ən.streɪt/ demo__n__strate
****_ recognize someone or sth and say or prove who or what they are:<b><color:red>identify
****_ questions whether it is true:<b><color:red>challenge
****_ look at or consider carefully and in detail:<b><color:red>Examine
****_ give :<b><color:red>Provide
****_ divide thing into groups __according to__ their type :<b><color:red>classify
****_ discover or get proof of :<b><color:red>establishing
****_ explain :<b><color:red>__account for__
****_ see is often used in the passive in academic style :<b><color:red>was seen
****_ given :<b><color:red>presented
****_ proved :<b><color:red>showed
****_ (formal) try :<b><color:red>attempt

*** VerbWithNoun
****_ __give/provide/offer an explanation__ (of/for) :<b><color:red>explain
****_ __carry out an exploration__ of:<b><color:red>explore
****_ __place/put <b><color:blue>emphasis</b>__ on --emphesi-- :<b><color:red>emphasise
****_ __give/provide a description__ of:<b><color:red>describe

****: pose(v)/pəʊz/
' the events pose a threat to stability in the region: Các sự kiện đe dọa sự ổn định trong khu vực
' she loves to pose for photographs in front of her fabulous house. cô ấy thích tạo dáng chụp ảnh trước ngôi nhà tuyệt vời của mình.
' the issue always generates a great deal of debate among academics. vấn đề này luôn tạo ra nhiều tranh luận giữa các học giả.
' In this theory of history, progress is closely identified with technology. Trong lý thuyết lịch sử này, sự tiến bộ được xác định chặt chẽ với công nghệ.
' the book attempts to explain the fundamental character of social life. cuốn sách cố gắng giải thích đặc điểm cơ bản của đời sống xã hội.
;

**[#lightgreen] Adj
**[#lightgreen] Adv
**[#lightgreen] Phrasal verb

'**[#lightblue] Leisure





@endmindmap