@startmindmap
caption English Vocabulary
'title Human

*[#Orange] <&flag>Academic \n Vocabulary


**[#lightgreen] Verb
***_ <b><color:red>devote(v) </b>cống hiến
**[#lightgreen] Phrasal verb

left side
**[#lightgreen] Noun
***_  sự phản ứng lại <b><color:red>(n)reaction

**[#lightgreen] Adj
***_:có đạo đức <b><color:red>(adj)moral
lòng can đảm <b><color:red>(adj)/ˈkʌr.ɪdʒ/ courage;
**[#lightgreen] Adv

'**[#lightblue] Leisure





@endmindmap