@startmindmap

*[#lightgreen] <&flag>Thanh
**[#orange] What I have
*** Soft Skill??


left side
**[#yellow] What I should improve

**[#red] What I have to learn
*** English
****[#cyan] <&flag>IELTS >= 6.5

right side
*[#lightgreen] <&flag>Companies
** VISA
** Master Card

left side
**[#orange] Singtel/NCS


right side
*[#lightgreen] <&flag>Situation
**[#red] disadvantage

left side
**[#orange] advantage

@endmindmap
