@startmindmap

*[#lightgreen] <&flag>Thanh
** What I believe to?
*** cause/result rule
**** Statistic
*** natural rule
*** social rule

** sport
*** Swim
*** <b><color:red>Badmi__n__ton
*** running
*** Bi da
****: <b><color:blue>__https://blattbilliards.com/blogs/news/how-to-play-pool-better__
- break
- hit
- cut;


@endmindmap
