@startmindmap
'https://canadadotnet.files.wordpress.com/2020/05/english-grammar-in-use-intermediate.pdf

'caption figure 1
'title My super title

*[#orange] <&flag>Tenses
**[#lightgreen] 1.Present
***[#pink] 10.1 Present Continuous \n<b>I'm doing
****_ I am doing something = I __started__ doing it and I __haven’t finished__; \n I’m in the middle of doing it.
****_ <b>getting,becoming  starting,beginning \n <b>...changing,improving increasing,raising,falling,growing
****:<b><color:red>verbs are NOT normally used in the present continuous
like want need prefer
know realise understand recognise
believe suppose remember mean
belong fit contain consist seem
;

***[#pink] 10.2 Present Simple \n<b>I do
****:<b>don't use for Continuous present
<b><color:red>see/hear/smell/taste;
****:<b>can use for both Simple and Continuous
<b><color:red>look/feel;


***[#lightblue] 10.3 Present Perfect \n<b>I have done
****_ for and since | when ...? | how long ...?
*****_ <b><color:red>__for__</b> + a period of time: \nfor two hours:from two hours ago until __now__
*****_ <b><color:red>__since__</b> + the start of a period: \nsince 2 o'clock:from 2 o'clock until __now__
*****_ <b><color:red>__when__</b> ...? + __past simple__
*****_ <b><color:red>__how long__</b> ...? + __present perfect__

****:how long have you (been) ...
<b><color:red>__Just__ = a short time ago
<b><color:red>__Already__ = sooner than expected
<b><color:red>__Yet__ = until now. We use yet to show that we are expecting something to happen.
__recently__, in the last few days, __so far__, __since__ I arrived
__for__ a long time, today, this evening, this year;
****_ When we say ‘something has happened’, this is usually new information
****_ When we use the present perfect, there is a connection with now. The action in the past has a result now
****[#lightblue] 10.3.1 Present Perfect Continuous \n<b>I have been doing

**[#lightgreen] 2.Past
***[#lightblue] 10.3 Past Simple \n<b>I did
****_ When Karen arrived, we had dinner. \n(= Karen arrived, and then we had dinner)
***[#lightblue] 10.4 Past Continuous \n I was doing
****_ When Karen arrived, we were having dinner. \n(= we had already started before she arrived)
***[#lightblue] 10.5 Past Perfect \n I have done
****[#lightblue] 10.5.1 Past Perfect Continuous\n I have been doing

**[#lightgreen] 3.Future
***:I'm going to (do)
will __and__ shall
I will __and__ I'm going to
will be doing __and__ will have done
;


**[#lightblue] 12.Relative clauses
**[#lightblue] 13.Adjectives and adverbs
**[#lightblue] 14.Conjunctions and prepositions
**[#lightblue] 15.Prepositions
**[#lightblue] 16.Phrasal Verbs


left side
'**[#lightblue] have __and__ have got
**[#lightblue] used to (do)
***:- thói quen trong quá khứ, hiện tại thì không
   -> nếu vẫn đúng ở hiện tại thì dùng hiện tại đơn
- điều gì đó đúng trong quá khứ nhưng không còn
đúng ở hiện tại;
**[#lightblue] 4.Modal
***: (be) able to
was/were able to | <b><color:red>__managed to__:
 -> sb <b><color:red>__successed__</b> in doing sth
must and can't;
***:<b><color:red>can(present)/could(past)
-> <b><color:red>__general ability__
+ infinitive(possible + allow)
see|hear|smell|taste|feel|remember|understand;
***:<b><color:red>1.can(realistic) vs 2.could(unrealistic, possible but less sure)
- in general >< not in general
2.could + verb (present)
<b><color:red>3.could + have + P1 (past)
- something is __possible__, but did not happened;
***:-<b><color:red> possible vs impossible
-<b><color:red> realistic vs unrealistic
-<b><color:red> in general vs not in general
-<b><color:red> Past vs Present vs Future
Note:  ;
***_ <b><color:red>might -> may -> could -> can -> should \n<b><color:red>-> would -> will -> must -> have to
**[#lightblue] 5.if and wish
**[#lightblue] 6.Passive
**[#lightblue] 7.Reported speech
**[#lightblue] 8.Questions and auxiliary verbs
**[#lightblue] 9.-ing and to
**[#lightblue] 10.Article and nouns
**[#lightblue] 11.Pronouns and determines



@endmindmap
